spring.application.name=pdflex-saas

server.port=8080

file.upload-dir=uploads/input/
file.output-dir=uploads/output/

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

ghostscript.path=gs

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
